services:
  - type: web
    name: hospital-appointment-backend
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL_REQUIRE
        value: "True"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
